*的使用

In [2]:
def function_1(*lisss):
    arguments = list(lisss)
    print(arguments)
    # 做题
    # 结果 return 或者 打印
    return None


# Calling the function with a list of numbers
r1 = function_1(2, 3, 4, 5, 6)
r2 = function_1()
r3 = function_1(1, 3, 5)

[2, 3, 4, 5, 6]
[]
[1, 3, 5]


质数问题的解决方案

In [ ]:
from math import sqrt


# 输入是一个整数

def p(n):
    sieve = [True] * (n + 1)
    
    # 10000
    
    # 100 * 100
    # 2* ....
    # 3* ...
    # 4* ...
    # 99 * ...
    # 100 * ...
    # 5000 * 2
    # 10 * 1000
    
    # 2
    
    
    # 欧拉筛
    for i in range(2, round(sqrt(n)) + 1):
        # 如果当前的i已经不是质数了
        # 就跳过
        if not sieve[i]:
            continue
        # for k  in   2*2, 2*3 , 2*4 , 2*5 , 2*6 ..... 2*50000 
        #             3*3, 3*4,  3*5,  3*6,  3*7, 3*8 ... 3*3333
        #             5*5  5*6,  5*7,  ....   5*2000
        #             7*7  7*8   .....
        # 
        for k in range(i * i, n + 1, i):
            sieve[k] = False
            
        # [2,3,5,7,11...9997]
    res = []
    for i in range(2, n + 1):
        if sieve[i]:
            res.append(i)
    return res

def primes(n):
    sieve = [True] * (n + 1)

    for i in range(2, round(sqrt(n)) + 1):
        if not sieve[i]:
            continue
        for k in range(i * i, n + 1, i):
            sieve[k] = False
    return [i for i in range(2, n + 1) if sieve[i]]




# 进行二次初始
print(p(100))
print(primes(100))


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [19]:
# 求出所有小于n的质数 且 质数的每一位不能有相同的元素
# 假设 23757 是一个质数 他有两个7所以 他不符合条件
# 43 就符合条件
# 求和 返回一个int
# 输出 是一个 列表
# 列表里的元素 是什么类型
def primes_2(n):
    sieve = [False, False] + ([True] * (n - 1))
    for i in range(2, round(sqrt(n)) + 1):
        if not sieve[i]:
            continue
        for k in range(i * i, n + 1, i):
            sieve[k] = False
    return sieve


def process(array):
    res = []
    for x in range(len(array)):
        if array[x]:
            res.append(x)
    return res


def sums_unique(n):
    result = primes_2(n)
    print(result)
    result = process(result)
    print(result)
    sums = 0
    for item in result:
        # 数字转成字符串
        # 取个len
        # 然后 字符串转换成集合
        # 取个len
        # 观察len是否变化
        str_item = str(item)
        set_item = set(str_item)
        if len(str_item) == len(set_item):
            sums += item
    return item


print(sums_unique(1000))

[False, False, True, True, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, True, False, False, False, False, False, True, False, False, False, True, False, False, False, False, False, True, False, False, False, False, False, False, False, True, False, False, False, True, False, True, False, False, False, True, False, True, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, True, False, False, False, False, False, True, False, True, False, False, False, False, False, False, False, Fals

In [121]:
from math import sqrt


def primes(n):
    sieve = [True] * (n + 1)
    for i in range(2, sqrt(n) + 1):
        if not sieve[i]:
            continue
        for k in range(i * 2, n + 1, i):
            sieve[k] = False
    return [i for i in range(2, n + 1) if sieve[i]]

什么是递归

In [ ]:
# 汉诺塔问题

#  1  |   |
#  2  |   |
#  3  |   |

#  |  |   |
#  2  |   |
#  3  |   1

#  |  |   |
#  |  |   |
#  3  2   1

#  |  |   |
#  |  1   |
#  3  2   |

#  |  |   |
#  |  1   |
#  |  2   3

#  |  |   |
#  |  |   |
#  1  2   3

#  |  |   |
#  |  |   2
#  1  |   3

#  |  |   1
#  |  |   2
#  |  |   3
#  A  B   C

# 过程中不允许有任何时候在任何柱子上 出现 倒着堆叠的情况

# 最少需要多少次

def hanoi(n, start_pos, end_pos, help_pos):
    # n = 3 st=A, ed=C hp=B
        # n = 2, st = A ed = B  hp = C
            # n = 1 st = A ed = C hp = B
                # size 1 from A to C
        #   <--- return
        # size 2 from A to B
            # n = 1, st=C, ed=B hp=A
                # size 1 from C to B
        #   <--- return
    # <--- return
    # size 3 from A to C
        # n = 2, st = A ed = B  hp = C
            # n = 1 st = A ed = C hp = B
                # size 1 from A to C
        #   <--- return
        # size 2 from A to B
            # n = 1, st=C, ed=B hp=A
                # size 1 from C to B
        #   <--- return
    if n > 1:
        hanoi(n - 1, start_pos, help_pos, end_pos)
    print(f"Move disk of size {n} from {start_pos} to {end_pos}")
    if n > 1:
        hanoi(n - 1, help_pos, end_pos, start_pos)


hanoi(3, "A", "C", "B")

Move disk of size 1 from A to C
Move disk of size 2 from A to B
Move disk of size 1 from C to B
Move disk of size 3 from A to C
Move disk of size 1 from B to A
Move disk of size 2 from B to C
Move disk of size 1 from A to C


In [ ]:
def hanoi_2(n, start_pos, end_pos, help_pos):
    stacks = list(range(n, 0, -1)), [], []
    smallest_disk_pos = 0
    direction = 1 if n % 2 == 0 else -1
    for i in range(2**n - 1):
        if i % 2 == 0:
            smallest_disk_new_pos = (smallest_disk_pos + direction) % 3
            print(
                f"Move smallest disk from {smallest_disk_pos} to {smallest_disk_new_pos}"
            )
            stacks[smallest_disk_new_pos].append(stacks[smallest_disk_pos].pop())
            smallest_disk_pos = smallest_disk_new_pos
        else:
            from_pos, to_pos = (smallest_disk_pos + 1) % 3, (smallest_disk_pos + 2) % 3
            if (
                not stacks[from_pos]
                or stacks[to_pos]
                and stacks[to_pos][-1] < stacks[from_pos][-1]
            ):
                from_pos, to_pos = to_pos, from_pos
            print(
                f"Move disk of size {stacks[from_pos][-1]} from {from_pos} to {to_pos}"
            )
            stacks[to_pos].append(stacks[from_pos].pop())
            
    # stuck 栈 数据结构
    
    # 先入后出
    
#         1
#     2      3
#   4   5  6   7




# 搜索到  节点2 和  节点3  stuck  [3,2]
# 来到节点 2 
# 搜索到  节点5 和 节点4   stuck [3, 5, 4]
# 来到 节点 4
# 没搜索到任何东西  stuck [3, 5]
# 来到 节点 5
# 没搜索到任何东西  stuck [3]
# 来到 节点 3
# 搜索到 节点 7 和 节点 6  stuck [7,6]
# 来到节点 6
# 来到节点 7



##   1 -- > 2  --> 4  --> 5 -->3 --> 6 --> 7 




hanoi_2(3, 0, 1, 2)

Move smallest disk from 0 to 2
Move disk of size 2 from 0 to 1
Move smallest disk from 2 to 1
Move disk of size 3 from 0 to 2
Move smallest disk from 1 to 0
Move disk of size 2 from 1 to 2
Move smallest disk from 0 to 2


In [24]:
l1=[2,3,5,6,2,4,5]

while l1:
    print(l1.pop())

5
4
2
6
5
3
2


DFS 路径问题模版

In [124]:
# 寻找连续最大的1
dim = 10

In [ ]:
# 9024 9020

In [ ]:
from random import seed, random
import sys

# 寻找连续的一片区域
dim = 10


def display(grid):
    with open("dfs3.txt", "w") as f:
        f.writelines("  " + "-" * (2 * dim + 3) + "\n")
        for row in grid:
            res = " ".join(row)
            f.writelines("  | " + f"{res}" + " |" + "\n")
        f.writelines("  " + "-" * (2 * dim + 3) + "\n")

    print("  ", "-" * (2 * dim + 3))
    for row in grid:
        print("   |", *row, "|")
    print("  ", "-" * (2 * dim + 3))


def dfs(i, j, grid, res):
    # 方向
    # 四方向
    direction = [[0, 1], [0, -1], [1, 0], [-1, 0]]
    # 越界返回 没有路返回
    if not (0 <= i < dim and 0 <= j < dim and grid[i][j] == "*"):
        return res
    if (i, j) in res:
        return res
    res.add((i, j))
    # 对于每个方向进行搜索
    for item in direction:
        dfs(i + item[0], j + item[1], grid, res)
    return res


def grrid(for_seed, i, j, density):
    try:
        if i < 1 or i > dim or j < 1 or j > dim or density < 0 or density > 1:
            raise ValueError
    except ValueError:
        print("Incorrect input, giving up.")
        sys.exit()
    seed(for_seed)
    grid = [
        ["*" if random() < density else " " for _ in range(dim)] for _ in range(dim)
    ]
    print("Here is the grid that has been generated:")
    display(grid)
    # 插入你的代码在这里
    # 以每个点为起点 都跑一遍dfs
    # 不难 因为 撑死 10*10 100次 * 4个方向 撑死 400次 * 格子数量 = 40000
    res = dfs(i, j, grid, set())
    # 可能你会定义其他函数
    news = []
    for x in range(dim):
        news.append([" "] * dim)
    for item in res:
        news[item[0]][item[1]] = "*"

    print("Here it is:")
    display(news)

In [ ]:
grrid(2, 2, 2, 0.5)

def dfs(i, j, grid, res):
    # 方向
    # 四方向
    direction = [[0, 1], [0, -1], [1, 0], [-1, 0]]
    # 越界返回 没有路返回
    if not (0 <= i < dim and 0 <= j < dim and grid[i][j] == "*"):
        return res
    if (i, j) in res:
        return res
    res.add((i, j))
    # 对于每个方向进行搜索
    for item in direction:
        dfs(i + item[0], j + item[1], grid, res)
    return res


Here is the grid that has been generated:
   -----------------------
   |     * *       *     |
   |   * * *         * * |
   | * * * * *       * * |
   | * *       *         |
   |     *     *     *   |
   | *       *     *     |
   |   * * *   *   *   * |
   |             * *     |
   |   *       *   *   * |
   | *   *     * *   *   |
   -----------------------
Here it is:
   -----------------------
   |     * *             |
   |   * * *             |
   | * * * * *           |
   | * *                 |
   |                     |
   |                     |
   |                     |
   |                     |
   |                     |
   |                     |
   -----------------------


In [26]:
from random import seed, random
import sys
import copy

# 寻找一条最长的路径
dim = 10


def display(grid):
    with open("dfs3.txt", "w") as f:
        f.writelines("  " + "-" * (2 * dim + 3) + "\n")
        for row in grid:
            res = " ".join(row)
            f.writelines("  | " + f"{res}" + " |" + "\n")
        f.writelines("  " + "-" * (2 * dim + 3) + "\n")

    print("  ", "-" * (2 * dim + 3))
    for row in grid:
        print("   |", *row, "|")
    print("  ", "-" * (2 * dim + 3))


def dfs2(i, j, target_i, target_j, grid, res, final_res):
    # 方向
    # 例如往 右方 和 下方
    direction = [[1, 1], [1, 0], [0, 1], [1, -1]]
    # 越界返回 没有路返回
    if not (0 <= i < dim and 0 <= j < dim and grid[i][j] == "*"):
        return final_res
    if i == target_i and j == target_j:
        res.add((i, j))
        if len(res) >= len(final_res):
            final_res = copy.deepcopy(res)
        return final_res
    if (i, j) in res:
        return final_res
    res.add((i, j))
    for item in direction:
        final_res = dfs2(
            i + item[0], j + item[1], target_j, target_j, grid, res, final_res
        )
    res.remove((i, j))
    return final_res


def grrid_2(for_seed, i, j, ti, tj, density):
    try:
        if i < 0 or i > dim or j < 0 or j > dim or density < 0 or density > 1:
            raise ValueError
    except ValueError:
        print("Incorrect input, giving up.")
        sys.exit()
    seed(for_seed)
    grid = [
        ["*" if random() < density else " " for _ in range(dim)] for _ in range(dim)
    ]
    print("Here is the grid that has been generated:")
    display(grid)
    final = dfs2(i, j, ti, tj, grid, set(), set())

    news = []
    for x in range(dim):
        news.append([" "] * dim)
    for item in final:
        news[item[0]][item[1]] = "*"

    print("Here it is:")
    display(news)


grrid_2(2, 1, 0, 8, 8, 0.7)

Here is the grid that has been generated:
   -----------------------
   |     * *     * * * * |
   | * * * *       * * * |
   | * * * * *   * * * * |
   | * * *   * *         |
   |     *     *     * * |
   | *   *   *     * *   |
   |   * * * * *   *   * |
   |     * * * * * * *   |
   | * *       *   * * * |
   | *   * *   * *   *   |
   -----------------------
Here it is:
   -----------------------
   |                     |
   | * *                 |
   | * *                 |
   | * * *               |
   |     *               |
   |     *               |
   |   * * *             |
   |     * * * * * * *   |
   |               * *   |
   |                     |
   -----------------------


In [129]:
from random import seed, random
import sys
import copy

# 寻找所有的路径
dim = 10


def display(grid):
    with open("dfs3.txt", "w") as f:
        f.writelines("  " + "-" * (2 * dim + 3) + "\n")
        for row in grid:
            res = " ".join(row)
            f.writelines("  | " + f"{res}" + " |" + "\n")
        f.writelines("  " + "-" * (2 * dim + 3) + "\n")

    print("  ", "-" * (2 * dim + 3))
    for row in grid:
        print("   |", *row, "|")
    print("  ", "-" * (2 * dim + 3))


def dfs3(i, j, target_i, target_j, grid, res, visited, final_res):
    # 方向 方向一定是有方向的 要么是往 下 或者 右下 或者上 或者右上 或者左上 否则会有环
    # 例如往 上下左右
    direction = [[0, 1], [0, -1], [-1, 0], [1, 0], [1, 1]]
    # 越界返回 没有路返回
    if not (0 <= i < dim and 0 <= j < dim and grid[i][j] == "*"):
        return False

    if i == target_i and j == target_j:
        res.add((i, j))
        final_res += list(res)
        return True
    if (i, j) in visited:
        if (i, j) in res:
            return False
    res.add((i, j))
    visited.add((i, j))
    flag = False
    for item in direction:
        if dfs3(
            i + item[0], j + item[1], target_j, target_j, grid, res, visited, final_res
        ):
            flag = True
    if not flag:
        res.remove((i, j))
    visited.remove((i, j))
    return flag


def grrid_3(for_seed, i, j, ti, tj, density):
    try:
        if i < 0 or i > dim or j < 0 or j > dim or density < 0 or density > 1:
            raise ValueError
    except ValueError:
        print("Incorrect input, giving up.")
        sys.exit()
    seed(for_seed)
    grid = [
        ["*" if random() < density else " " for _ in range(dim)] for _ in range(dim)
    ]
    print("Here is the grid that has been generated:")
    display(grid)
    final = []
    dfs3(i, j, ti, tj, grid, set(), set(), final)

    news = []
    for x in range(dim):
        news.append([" "] * dim)
    for item in final:
        news[item[0]][item[1]] = "*"

    print("Here it is:")
    display(news)


grrid_3(2, 1, 0, 8, 8, 0.7)

Here is the grid that has been generated:
   -----------------------
   |     * *     * * * * |
   | * * * *       * * * |
   | * * * * *   * * * * |
   | * * *   * *         |
   |     *     *     * * |
   | *   *   *     * *   |
   |   * * * * *   *   * |
   |     * * * * * * *   |
   | * *       *   * * * |
   | *   * *   * *   *   |
   -----------------------
Here it is:
   -----------------------
   |     * *             |
   | * * * *             |
   | * * * * *           |
   | * * *               |
   |     *               |
   |     *   *           |
   |   * * * * *   *     |
   |     * * * * * * *   |
   |           *   * * * |
   |                 *   |
   -----------------------


In [130]:
from random import seed, random
import sys
import copy

# 升级 对于全方向 寻找一条最长的路径
dim = 10


def display(grid):
    with open("dfs3.txt", "w") as f:
        f.writelines("  " + "-" * (2 * dim + 3) + "\n")
        for row in grid:
            res = " ".join(row)
            f.writelines("  | " + f"{res}" + " |" + "\n")
        f.writelines("  " + "-" * (2 * dim + 3) + "\n")

    print("  ", "-" * (2 * dim + 3))
    for row in grid:
        print("   |", *row, "|")
    print("  ", "-" * (2 * dim + 3))


def dfs4(i, j, target_i, target_j, grid, res, final_res):
    # 方向 方向一定是有方向的 要么是往 下 或者 右下 或者上 或者右上 或者左上 否则会有环
    # 例如往 右方 和 下方
    direction = [[0, 1], [1, 0], [-1, 0], [0, -1], [1, 1]]
    # 越界返回 没有路返回
    if not (0 <= i < dim and 0 <= j < dim and grid[i][j] == "*"):
        return final_res
    if i == target_i and j == target_j:
        res.add((i, j))
        if len(res) >= len(final_res):
            final_res = copy.deepcopy(res)
        res.remove((i, j))
        return final_res
    if (i, j) in res:
        return final_res
    res.add((i, j))
    for item in direction:
        final_res = dfs4(
            i + item[0], j + item[1], target_i, target_j, grid, res, final_res
        )
    res.remove((i, j))
    return final_res


def grrid_4(for_seed, i, j, ti, tj, density):
    try:
        if i < 0 or i > dim or j < 0 or j > dim or density < 0 or density > 1:
            raise ValueError
    except ValueError:
        print("Incorrect input, giving up.")
        sys.exit()
    seed(for_seed)
    grid = [
        ["*" if random() < density else " " for _ in range(dim)] for _ in range(dim)
    ]
    print("Here is the grid that has been generated:")
    display(grid)
    final = dfs4(i, j, ti, tj, grid, set(), set())

    news = []
    for x in range(dim):
        news.append([" "] * dim)
    for item in final:
        news[item[0]][item[1]] = "*"

    print("Here it is:")
    display(news)


grrid_4(2, 1, 0, 8, 8, 0.7)

Here is the grid that has been generated:
   -----------------------
   |     * *     * * * * |
   | * * * *       * * * |
   | * * * * *   * * * * |
   | * * *   * *         |
   |     *     *     * * |
   | *   *   *     * *   |
   |   * * * * *   *   * |
   |     * * * * * * *   |
   | * *       *   * * * |
   | *   * *   * *   *   |
   -----------------------
Here it is:
   -----------------------
   |     * *             |
   | * * * *             |
   | * * * * *           |
   | * * *               |
   |     *               |
   |     *   *           |
   |   * * * * *   *     |
   |     * * * * * * *   |
   |               * * * |
   |                     |
   -----------------------


字典树的递归 与类的复习

In [ ]:
import copy


# 1.定义一个节点
class Node:
    def __init__(self):
        # 当前节点的所有直系子节点
        # 元素的key是一个 字母
        # 元素的值是一个 节点
        self.all_child = {}
        # 当前节点是否有单词结束
        self.isEnd = False
        # 当前单词是什么
        self.current_word = None

    def __repr__(self) -> str:
        return f"{self.all_child}"


# 2.定义一个 字典树
class Tire:
    def __init__(self):
        # 根节点
        self.root = Node()
        # 最长的单词
        self.max_length = 0
        # 每个长度的单词都有多少
        self.word_by_length = {}
        # 记忆
        # 记录当前pattern的搜索结果
        # 如果在遇到相同的pattern我们就不搜索了

        # 直接用之前的记忆
        self.memory = {}

    # 向字典树里插入一个单词
    def insert_node(self, word):
        current_node = self.root
        for char in word:
            # print(current_node.all_child)
            # 查找当前节点有没有这个char
            # 如果没有 就插入以当前char为key的节点
            if char not in current_node.all_child:
                current_node.all_child[char] = Node()
            # 我们要进去的节点
            # 如果有 就直接进入 当前char 的节点
            target = current_node.all_child[char]
            current_node = target
        current_node.isEnd = True
        current_node.current_word = word

    # 这里同学们要会变通 !!!!
    # 可以改成返回单词
    # 而且我们的pattern可以是任何形式 例如 数组 字符串 集合 都可以进行搜索
    # 主要是要懂逻辑 而不是死背代码
    def search(self, node: Node, index, pattern, result, target_index):
        if index == len(pattern):
            if node.isEnd:
                result.add(node.current_word[target_index])
            return
        current_char = pattern[index]

        if current_char == "*":
            for item in node.all_child:
                target_node = node.all_child[item]
                self.search(target_node, index + 1, pattern, result, target_index)
        else:
            if current_char in node.all_child:
                target_node = node.all_child[current_char]
                self.search(target_node, index + 1, pattern, result, target_index)
        return

    def search_word(self, node: Node, pattern: list, result):
        if not pattern:
            if node.isEnd:
                result.add(node.current_word)
            return
        for item in pattern:
            new_pattern = copy.deepcopy(pattern)
            new_pattern.remove(item)
            if item in node.all_child:
                new_node = node.all_child[item]
                self.search_word(new_node, new_pattern, result)
        return


# 3.完成往字典树里添加一个单词的算法
# 创建一个节点
# 把节点插入字典树
# 移动到下一个节点

# 4.完成在字典树里寻找相应单词模式的方法

# 5.利用字典树, 把单词插进去

tree = Tire()

with open("dictionary.txt", "r") as f:
    for item in f:
        tree.insert_node("".join(item.split()))
print(tree.root)
result = set()
tree.search_word(tree.root, ["R", "O", "C", "K"], result)
print(result)

{'A': {'A': {'R': {'H': {'U': {'S': {}}}, 'O': {'N': {}}}}, 'B': {'A': {'B': {'A': {}}, 'C': {'K': {}}, 'F': {'T': {}}, 'N': {'D': {'O': {'N': {'E': {'D': {}}, 'I': {'N': {'G': {}}}, 'M': {'E': {'N': {'T': {}}}}, 'S': {}}}}}, 'S': {'E': {'D': {}, 'M': {'E': {'N': {'T': {'S': {}}}}}, 'S': {}}, 'H': {'E': {'D': {}, 'S': {}}, 'I': {'N': {'G': {}}}}, 'I': {'N': {'G': {}}}}, 'T': {'E': {'D': {}, 'M': {'E': {'N': {'T': {'S': {}}}}}, 'R': {}, 'S': {}}, 'I': {'N': {'G': {}}}}}, 'B': {'A': {}, 'E': {'Y': {'S': {}}}, 'O': {'T': {'S': {}, 'T': {}}}, 'R': {'E': {'V': {'I': {'A': {'T': {'E': {'D': {}, 'S': {}}, 'I': {'N': {'G': {}}, 'O': {'N': {'S': {}}}}}}}}}}, 'Y': {}}, 'D': {'O': {'M': {'E': {'N': {'S': {}}}, 'I': {'N': {'A': {'L': {}}}}}}, 'U': {'C': {'T': {'E': {'D': {}}, 'I': {'O': {'N': {'S': {}}}}, 'O': {'R': {'S': {}}}, 'S': {}}}}}, 'E': {'D': {}, 'L': {'I': {'A': {'N': {}}}, 'S': {'O': {'N': {}}}}, 'R': {'D': {'E': {'E': {'N': {}}}}, 'N': {'A': {'T': {'H': {'Y': {}}}}}, 'R': {'A': {'N': {

numpy的使用

NumPy 创建数组

ndarray 数组除了可以使用底层 ndarray 构造器来创建外，也可以通过以下几种方式来创建。

numpy.empty

numpy.empty 方法用来创建一个指定形状（shape）、数据类型（dtype）且未初始化的数组：

numpy.empty(shape, dtype = float, order = 'C')

In [27]:
import numpy as np

x = np.empty([3, 2], dtype=int)
print(x)

[[-1152921504606846976 -1152921504606846976]
 [                   7                    0]
 [                   0                    0]]


注意 − 数组元素为随机值，因为它们未初始化。

创建指定大小的数组，数组元素以 0 来填充：

numpy.zeros(shape, dtype = float, order = 'C')

In [ ]:
import numpy as np

# 默认为浮点数
x = np.zeros(5)
print(x)

# 设置类型为整数
y = np.zeros((5,), dtype=int)
print(y)

# 自定义类型
z = np.zeros((2, 2), dtype=[("x", "i4"), ("y", "i4")])
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


numpy.ones

创建指定形状的数组，数组元素以 1 来填充：

numpy.ones(shape, dtype = None, order = 'C')

In [ ]:
import numpy as np

# 默认为浮点数
x = np.ones(5)
print(x)

# 自定义类型
x = np.ones([2, 2], dtype=int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


numpy.zeros_like

numpy.zeros_like 用于创建一个与给定数组具有相同形状的数组，数组元素以 0 来填充。

numpy.zeros 和 numpy.zeros_like 都是用于创建一个指定形状的数组，其中所有元素都是 0。

它们之间的区别在于：numpy.zeros 可以直接指定要创建的数组的形状，而 numpy.zeros_like 则是创建一个与给定数组具有相同形状的数组。

numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)

In [ ]:
import numpy as np

# 创建一个 3x3 的二维数组
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 创建一个与 arr 形状相同的，所有元素都为 0 的数组
zeros_arr = np.zeros_like(arr)
print(zeros_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


numpy.arange

numpy 包中的使用 arange 函数创建数值范围并返回 ndarray 对象，函数格式如下：

numpy.arange(start, stop, step, dtype)

根据 start 与 stop 指定的范围以及 step 设定的步长，生成一个 ndarray。

In [ ]:
import numpy as np

x = np.arange(5)
print(x)

[0 1 2 3 4]


In [ ]:
import numpy as np

# 设置了 dtype
x = np.arange(5, dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [ ]:
import numpy as np

x = np.arange(10, 20, 2)
print(x)

[10 12 14 16 18]


numpy.linspace

numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：

np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)


In [30]:
import numpy as np

a = np.linspace(2, 10, 5)
print(a)

[ 2.  4.  6.  8. 10.]


NumPy 切片和索引

ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样。

ndarray 数组可以基于 0 - n 的下标进行索引，切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。

In [ ]:
import numpy as np

a = np.arange(10)
s = slice(2, 7, 2)  # 从索引 2 开始到索引 7 停止，间隔为2
print(a[s])

[2 4 6]


以上实例中，我们首先通过 arange() 函数创建 ndarray 对象。 然后，分别设置起始，终止和步长的参数为 2，7 和 2。

我们也可以通过冒号分隔切片参数 start:stop:step 来进行切片操作：

In [ ]:
import numpy as np

a = np.arange(10)
b = a[2:7:2]  # 从索引 2 开始到索引 7 停止，间隔为 2
print(b)

[2 4 6]


整数数组索引

整数数组索引是指使用一个数组来访问另一个数组的元素。这个数组中的每个元素都是目标数组中某个维度上的索引值。

以下实例获取数组中 (0,0)，(1,1) 和 (2,0) 位置处的元素。

In [12]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
print(y)

[1 4 5]


以下实例获取了 4X3 数组中的四个角的元素。 行索引是 [0,0] 和 [3,3]，而列索引是 [0,2] 和 [0,2]。

In [33]:
import numpy as np

x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print("我们的数组是：")
print(x)
print("\n")
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
y = x[rows, cols]
print("这个数组的四个角元素是：")
print(y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]


可以借助切片 : 或 … 与索引数组组合。如下面例子：

In [32]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = a[1:3, 1:3]
c = a[1:3, [1, 2]]
d = a[..., 1:]
print(b)
print(c)
print(d)

print(a[:,2])
print(a[2,:])

[[5 6]
 [8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]
[3 6 9]
[7 8 9]


一些简单的算法解释

二分查找

在一个有序列表中寻找一个值 K, 不存在就返回 -1


10*10

机器 能够扫描半个目标

怎么用最少次数

先扫描 5*10 如果有 在有的里找 如果没有 就去另一块找

5*5


2.5 * 5

2.5 * 2.5

1.25 * 2.5

1.25 * 1.25

In [ ]:

def binary_search(arr, K):
    low = 0
    high = len(arr) - 1
    
    while low <= high:
        mid = (low + high) // 2
        
        # 如果中间元素是目标值，返回其索引
        if arr[mid] == K:
            return mid
        # 如果目标值较大，排除左半部分
        elif arr[mid] < K:
            low = mid + 1
        # 如果目标值较小，排除右半部分
        else:
            high = mid - 1
    
    # 如果没有找到目标值，返回 -1
    return -1



binary_search([1, 3, 6, 7, 10, 12, 14, 20], 20)

4

递归
斐波那契数列

In [ ]:
# 1,1,2,3,5,8,13


def fibonacci(n):
    if n <= 1:
        print(n, end=", ")
        return n
        #  n = 4                                                # n = 3
        #  n = 3                                                # 1 + 0 + 1
        #  n = 2             # n = 1
        #  n = 1,  n = 0
        #  return    1 + 0 + 1
        #  return    f(5) = f(4) + f(3) 
        #                 = f(3) + f(2) + f(3) 
        #                 = f(2) + f(1) + f(2) + f(3) 
        #                 = f(1) + f(0) + f(1) + f(2) + f(3) 
        #                 = 1 + 0       + f(1) 
        #                 = 1 + 0 +  1  + f(2) + f(3)  
        #                 = 1 + 0 +  1  + f(1) + f(0) + f(3)
        #                 = 1 + 0 + 1   + 1    + 0    + f(3) 
        #                 = 1 + 0 + 1   + 1    + 0    + f(2) +f(1) 
        #                 = 1 + 0 + 1   + 1    + 0    + f(1）+f(0) +f(1) 
        #                 = 1 + 0 + 1   + 1    + 0    + 1    + 0   + 1
    res = fibonacci(n - 1) + fibonacci(n - 2)
    print(res, end=", ")
    return res


fibonacci(5)

1, 0, 1, 1, 2, 1, 0, 1, 3, 1, 0, 1, 1, 2, 5, 

5

贪心算法


贪心算法


问题：给定n种不同面值的硬币，分别记为c[0], c[1], c[2], … c[n]，同时还有一个总金额k，

编写一个函数计算出最少需要几枚硬币凑出这个金额k？每种硬币的个数不限，且如果没有任何一种硬币组合能组成总金额时，返回 -1。

In [32]:
def change(coins, amount):

    coins.sort(reverse=True)

    count = 0
    for coin in coins:
        # 选择当前面值能用的最多数量
        if amount >= coin:
            num = amount // coin  # 使用的该面值硬币数量
            count += num  # 增加总硬币数
            amount -= num * coin  # 更新剩余金额

        # 如果已经凑出金额则直接返回
        if amount == 0:
            return count

    # 如果金额不为0，表示无法凑出该金额
    return -1


change([1, 5, 10, 20, 50, 100], 67)

5

动态规划
最长递增子序列 是指在一个数组中找到一个子序列，它的数值严格递增，

并且使这个子序列的长度尽可能长。 最长递增子序列的元素在原序列中不一定是连续的。

例如 A = [10,9,2,5,3,7,101,18] 的最长递增子序列是 [2,3,7,101]，其长度是 4 。



In [31]:
def length_of_lis(nums):
    # 特殊情况：如果数组为空，则返回 0
    if not nums:
        return 0

    # 创建 dp 数组，初始时每个元素的 LIS 长度为 1
    # dp[i] 表示以 nums[i] 为结尾的最长递增子序列的长度
    dp = [1] * len(nums)
    # 遍历数组
    print(f'initial array is {nums}')
    for i in range(1, len(nums)):
        # 对于每一个元素 nums[i]，遍历它之前的所有元素 nums[j]
        print(f'Now i = {i}')
        for j in range(i):
            print(f'Now j = {j}, dp arrray is {dp}')
            # 如果 nums[j] < nums[i]，则 nums[i] 可以接在 nums[j] 后面形成递增序列
            # 更新 dp[i]，选择 dp[i] 和 dp[j] + 1 中的较大值
            if nums[j] < nums[i]:
                dp[i] = max(dp[i], dp[j] + 1)
        print()
    # 返回 dp 数组中的最大值，即最长递增子序列的长度
    return max(dp)


length_of_lis([10, 9, 2, 5, 3, 3, 7, 101, 102, 18])

initial array is [10, 9, 2, 5, 3, 3, 7, 101, 102, 18]
Now i = 1
Now j = 0, dp arrray is [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Now i = 2
Now j = 0, dp arrray is [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Now j = 1, dp arrray is [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Now i = 3
Now j = 0, dp arrray is [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Now j = 1, dp arrray is [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Now j = 2, dp arrray is [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

Now i = 4
Now j = 0, dp arrray is [1, 1, 1, 2, 1, 1, 1, 1, 1, 1]
Now j = 1, dp arrray is [1, 1, 1, 2, 1, 1, 1, 1, 1, 1]
Now j = 2, dp arrray is [1, 1, 1, 2, 1, 1, 1, 1, 1, 1]
Now j = 3, dp arrray is [1, 1, 1, 2, 2, 1, 1, 1, 1, 1]

Now i = 5
Now j = 0, dp arrray is [1, 1, 1, 2, 2, 1, 1, 1, 1, 1]
Now j = 1, dp arrray is [1, 1, 1, 2, 2, 1, 1, 1, 1, 1]
Now j = 2, dp arrray is [1, 1, 1, 2, 2, 1, 1, 1, 1, 1]
Now j = 3, dp arrray is [1, 1, 1, 2, 2, 2, 1, 1, 1, 1]
Now j = 4, dp arrray is [1, 1, 1, 2, 2, 2, 1, 1, 1, 1]

Now i = 6
Now j = 0, dp arrray is [1, 1, 1, 2, 2, 2, 1, 1, 1, 1]
N

5